---
abstract: 'Moose Roles for building next generation DateTime formats'
author:
  - 'Evan Carroll <me@evancarroll.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Format
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  DateTime: 0
  DateTime::Locale: 0
  DateTime::TimeZone: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Types::DateTime::ButMaintained: 0.07
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git@github.com:EvanCarroll/datetimex-format.git
version: 1.02
